export type Category = {
    id: number
    displayNum: string
    name: string
    icon: string
    description: string
    criteria: string[]
    isLegacy?: boolean
}

export const CATEGORIES: Category[] = [
    { id: 1,  displayNum: "01", name: "Founder of the Year",              icon: "👑", description: "The flagship award. Any individual on a qualifying route who has launched and is actively operating a UK-based business. No minimum revenue. Judged on innovation, impact and trajectory.", criteria: ["Innovation and originality of the business model", "Demonstrable UK economic, social or sector impact", "Growth trajectory and evidence of traction"] },
    { id: 2,  displayNum: "02", name: "Tech & Deep Science Innovation",   icon: "🔬", description: "Founders, researchers and teams in AI, biotech, climate tech, quantum, robotics or any deep science or engineering field. Must have a functioning product, prototype or peer-reviewed research output.", criteria: ["Technical innovation and originality", "Commercial or research validation", "Potential for significant societal or economic impact"] },
    { id: 3,  displayNum: "03", name: "Global Talent Award",              icon: "🌍", description: "For Global Talent Visa holders who have made an exceptional contribution to UK innovation, culture, science, technology or business, whether as a founder, employee, researcher, creative or independent expert.", criteria: ["Measurable contribution to a UK organisation, institution or project", "International reputation or peer recognition", "Evidence of knowledge or skills transfer to UK teams"] },
    { id: 4,  displayNum: "04", name: "Emerging Founder of the Year",     icon: "🚀", description: "Recognising a founder building an ambitious UK business who has demonstrated meaningful early market validation, momentum and potential for significant growth.", criteria: ["Evidence of early market validation, including customers, users, pilots, revenue or commercial partnerships", "Quality of execution and progress achieved relative to the age and stage of the business", "Strength of the founder's vision, leadership and credible potential to build a significant UK business"] },
    { id: 5,  displayNum: "05", name: "Co-Founding Team of the Year",     icon: "🤝", description: "For a UK-based company co-founded by two or more individuals who were all active within three months of formation. To be eligible at least one co-founder is/was on a qualifying route.", criteria: ["The complementarity of the founding team, how the co-founders' skills, backgrounds and perspectives combine", "Evidence that the co-founding dynamic has been a genuine driver of the company's success", "Business performance and growth trajectory"] },
    { id: 6,  displayNum: "06", name: "Rising Star",                      icon: "🌟", description: "Individual on a qualifying route, aged 35 or under, who has launched a UK business within the last three years. Pre-revenue businesses eligible and encouraged.", criteria: ["Originality and ambition of the business idea", "Speed of progress relative to time since founding and available resources", "Early signals of traction, validation or market interest"] },
    { id: 7,  displayNum: "07", name: "Creative & Cultural Innovation",   icon: "🎨", description: "For founders, researchers, practitioners or creative leaders on a qualifying route in fashion, design, media, music, film, architecture, food, arts or culture (or equivalent sectors), who have built a significant UK presence or platform.", criteria: ["Creative originality and cultural distinctiveness", "Significance of UK platform, audience or institutional recognition", "Commercial viability or critical acclaim"] },
    { id: 8,  displayNum: "08", name: "UK SME Global Expansion",          icon: "🌐", description: "For UK-headquartered businesses with fewer than 250 employees, with a founder or co-founder on a qualifying route, that have demonstrated real traction in at least one overseas market.", criteria: ["Evidence of successful international market entry: revenue, partnerships, customers", "Strategic approach to global expansion, how they identified and entered the market", "UK jobs and capabilities retained while scaling internationally"] },
    { id: 9,  displayNum: "09", name: "Breakthrough Innovation of the Year", icon: "💡", description: "For the single most original or disruptive idea commercialised in the UK by a founder, researcher or team on a qualifying route in the last 24 months. Revenue and scale are irrelevant; originality is everything.", criteria: ["Originality, how novel is the idea relative to what exists in the market or field", "Potential for significant impact: commercial, scientific, social or cultural", "Evidence of commercialisation: prototype, customer, deployment or equivalent"] },
    { id: 10, displayNum: "10", name: "Ecosystem Builder of the Year",    icon: "🏗️", description: "Incubators, accelerators, VC funds, universities, government bodies, law firms or individual champions who have demonstrably supported founders or global talent on qualifying routes in the UK.", criteria: ["Number and calibre of qualifying-route founders or talent supported", "Specific programmes or initiatives serving this community", "Advocacy and public voice for the international innovation community"] },
    { id: 11, displayNum: "XX", name: "Pioneer Award",                    icon: "🏆", description: "(Nomination only, not open for self-entry) Special recognition for individuals who came to the UK under an earlier innovation route and built something of lasting significance, before today's framework existed.", criteria: ["Scale and longevity of the UK business or contribution", "Legacy impact on their sector or the broader innovation ecosystem", "Role as mentor, investor or ecosystem builder for the next generation", "Recognition by peers, institutions and the media"], isLegacy: true },
]
