export type Category = {
    id: number
    displayNum: string
    name: string
    icon: string
    description: string
    criteria: string[]
    isLegacy?: boolean
}

export const CATEGORIES: Category[] = [
    { id: 1,  displayNum: "01", name: "Founder of the Year",              icon: "👑", description: "The flagship award for any individual on a qualifying route who has launched and is actively operating a UK-based business.", criteria: ["Innovation and originality of the business model", "Demonstrable UK economic, social or sector impact", "Growth trajectory and evidence of traction", "Contribution to the wider UK innovation ecosystem"] },
    { id: 2,  displayNum: "02", name: "Tech & Deep Science Innovation",   icon: "🔬", description: "For founders, researchers and teams in AI, biotech, climate tech, quantum, robotics or any deep science or engineering field with a functioning product, prototype or peer-reviewed research output.", criteria: ["Technical innovation and originality", "Commercial or research validation", "UK R&D footprint and talent", "Potential for significant societal or economic impact"] },
    { id: 3,  displayNum: "03", name: "Global Talent Award",              icon: "🌍", description: "For Global Talent Visa holders who have made an exceptional contribution to UK innovation, culture, science, technology or business, whether as a founder, employee, researcher, creative or independent expert.", criteria: ["Exceptional skill or expertise recognised by a UK endorsing body", "Measurable contribution to a UK organisation or project", "International reputation or peer recognition", "Evidence of knowledge or skills transfer to UK teams"] },
    { id: 4,  displayNum: "04", name: "Scale-Up of the Year",            icon: "📈", description: "For a UK business founded or co-founded by someone on a qualifying route that has achieved significant scale in the last 12–24 months.", criteria: ["Revenue or user growth year on year", "UK team growth and quality of hiring", "Market expansion or new product lines", "Fundraising milestone or path to profitability"] },
    { id: 5,  displayNum: "05", name: "Co-Founding Team of the Year",     icon: "🤝", description: "For a UK-based company co-founded by two or more individuals on qualifying routes who were all active within three months of formation.", criteria: ["Complementarity of the founding team's skills and perspectives", "Evidence the co-founding dynamic drove the company's success", "Business performance and growth trajectory", "Founding story and culture built around the partnership"] },
    { id: 6,  displayNum: "06", name: "Rising Star",                      icon: "🌟", description: "For an individual on a qualifying route, aged 35 or under, who has launched a UK business within the last three years. Pre-revenue businesses eligible and encouraged.", criteria: ["Originality and ambition of the business idea", "Speed of progress relative to time and available resources", "Founder mindset: resilience, adaptability, clarity under pressure", "Early signals of traction or market interest"] },
    { id: 7,  displayNum: "07", name: "Creative & Cultural Innovation",   icon: "🎨", description: "For founders, researchers, practitioners or creative leaders on a qualifying route in fashion, design, media, music, film, architecture, food, arts or culture who have built a significant UK presence or platform.", criteria: ["Creative originality and cultural distinctiveness", "Significance of UK platform, audience or institutional recognition", "Commercial viability or critical acclaim", "How an international perspective shaped their UK work"] },
    { id: 8,  displayNum: "08", name: "UK SME Global Expansion",          icon: "🌐", description: "For UK-headquartered businesses with fewer than 250 employees, with a founder or co-founder on a qualifying route, that have demonstrated real traction in at least one overseas market.", criteria: ["Evidence of successful international market entry", "Strategic approach to identifying and entering new markets", "Challenges overcome operating across borders and cultures", "UK jobs and capabilities retained while scaling internationally"] },
    { id: 9,  displayNum: "09", name: "Breakthrough Innovation of the Year", icon: "💡", description: "For the single most original or disruptive idea commercialised in the UK by a founder, researcher or team on a qualifying route in the last 24 months. Revenue and scale are irrelevant; originality is everything.", criteria: ["Originality relative to what exists in the market or field", "Potential for significant commercial, scientific or social impact", "Evidence of commercialisation: prototype, customer or deployment", "The insight, what did they see that others missed"] },
    { id: 10, displayNum: "10", name: "Ecosystem Builder of the Year",    icon: "🏗️", description: "For an incubator, accelerator, VC fund, university, government body, law firm or individual champion who has demonstrably supported founders or global talent on qualifying routes in the UK.", criteria: ["Number and calibre of qualifying-route founders or talent supported", "Specific programmes or initiatives serving this community", "Track record of outcomes: funding raised, jobs created, exits", "Advocacy for the international innovation community"] },
    { id: 11, displayNum: "XX", name: "Pioneer Award",                    icon: "🏆", description: "(Nomination only, not open for self-entry) Special recognition for individuals who came to the UK under an earlier innovation route and built something of lasting significance, before today's framework existed.", criteria: ["Scale and longevity of the UK business or contribution", "Legacy impact on their sector or the broader innovation ecosystem", "Role as mentor, investor or ecosystem builder for the next generation", "Recognition by peers, institutions and the media"], isLegacy: true },
]
