export type Faq = { q: string; a: string }

export const FAQS: Faq[] = [
    { q: "What are the Global Innovator Awards?", a: "The Global Innovator Awards is the UK's first awards programme dedicated to recognising founders, innovators and exceptional talent who came to the UK under a qualifying innovation or talent route, and are delivering on their ambition here. The awards are free to enter, independently judged, and cover 10 competitive categories plus the honorary Pioneer Award. The awards evening takes place in Central London on 16 November 2026." },
    { q: "Who is eligible to enter?", a: "The awards are open to founders, innovators and exceptional talent who made an active decision to come to the UK under one of the following qualifying routes: Global Talent Visa (current); Innovator Founder Visa (current); Graduate Visa (current); Innovator Visa (previous route, closed 2023); Start-up Visa (legacy); Tier 1 Exceptional Talent (legacy); or Tier 1 Entrepreneur (legacy). Eligibility is based on the route taken, not your country of birth or nationality. You do not need to be on the visa now, previous holders are eligible." },
    { q: "Is there a fee to enter?", a: "No. Entry and nomination are completely free. There is no fee at any stage of the awards process. Attending the awards evening as a ticket holder is subject to a separate ticket purchase, but entering and nominating cost nothing." },
    { q: "Can I nominate myself, or does someone else need to nominate me?", a: "Both are welcome. Self-nomination is actively encouraged, many of the founders and innovators who have achieved the most will not be nominated by others unless they put themselves forward. Third-party nominations are equally accepted. If someone nominates you without your prior knowledge, we will contact you promptly to let you know and give you the option to proceed or withdraw." },
    { q: "How does the entry process work?", a: "The awards use a two-stage process. Stage one was an open nominations period, free, quick, and under five minutes to complete. Nominations closed on Friday 28th August. Longlisted nominees are invited to complete a full stage two submission by Friday 4th September. Stage two submissions go to our independent judging panel, who rank their top ten. Ten finalists per category are announced in September. Winners are revealed at the awards evening in November." },
    { q: "How many categories are there and which one should I enter?", a: "There are 10 competitive categories plus the honorary Pioneer Award (nomination only). The categories are: Founder of the Year; Tech & Deep Science Innovation; Global Talent Award; Scale-Up of the Year; Co-Founding Team of the Year; Rising Star; Creative & Cultural Innovation; UK SME Global Expansion; Breakthrough Innovation of the Year; and Ecosystem Builder of the Year. Start by reading the category descriptions on the website to find the best fit. You can enter more than one category if you meet the criteria for each." },
    { q: "I'm on the Global Talent Visa but I'm not a founder. Can I enter?", a: "Yes. The Global Talent Award category is specifically for Global Talent Visa holders, Exceptional Promise or Exceptional Talent endorsement, and is open to founders, employees, researchers, artists, designers and independent experts alike. If you hold the Global Talent Visa and have also founded a business, you are equally eligible to enter Categories 01, 02, 04, 05, 06, 07, 08 and 09 where you meet the criteria for those categories." },
    { q: "I previously held a qualifying visa but it has since lapsed or I've become a British citizen. Am I still eligible?", a: "Yes. You do not need to be on the visa at the time of nomination. The key criterion is that you originally came to the UK under one of the qualifying routes. Previous holders, settled residents, and those who have since become British citizens are all eligible, provided they made an active adult decision to come to the UK under a qualifying route." },
    { q: "How are finalists and winners selected?", a: "Finalists are selected by an independent judge panel. Each judge is allocated to one category and ranks their top ten nominees from the stage two submissions. Aggregate rankings across all judges determine the ten publicly announced finalists per category. The highest-scoring nominee in each category is the winner, but this is not disclosed until the awards evening. Judging decisions are final." },
    { q: "Do sponsors influence the judging?", a: "No. Sponsors have absolutely no access to submissions, judge rankings, or winner decisions at any stage. Sponsoring a category gives naming rights and commercial visibility, it has no bearing on the judging outcome. All submission content is confidential and accessible only to the awards team and the relevant category judges." },
    { q: "Will my submission be kept confidential?", a: "Yes. Submission content submitted as part of your stage two entry will not be published or shared publicly without your prior written consent. Your submission is shared only with the awards team and the relevant category judge(s) for assessment purposes. It will not be shared with sponsors, media partners or any other third party." },
    { q: "What do finalists and winners receive?", a: "Finalists are featured on the awards website, in press communications and on social media. They receive a finalist digital badge and social media kit, issued within three working days of the shortlist announcement, and a discounted ticket to the awards evening. Winners receive a physical trophy presented on the night, a winner digital badge and social media kit (issued within 24 hours of the ceremony), coverage across our media partner network, and a podcast feature spotlighting their story. There is no cash prize." },
    { q: "How do I buy a ticket to the awards evening?", a: "Tickets go on sale in September 2026 via the website. Join the waitlist on globalinnovatorawards.com now for priority access and an early bird discount. Finalists receive a unique discounted ticket code communicated directly to them by the events team after the shortlist announcement. All ticket sales are final. Refunds are available only if the event is cancelled or rescheduled with no alternative date offered." },
    { q: "How do I contact the team if I have a question not answered here?", a: "The quickest way to reach us is via the live chat on globalinnovatorawards.com. You can also use the contact form on the website. We aim to respond within 24 hours." },
]
