export type FinalistGroup = {
    displayNum: string
    category: string
    names: string[]
}

/** 2026 shortlist: ten finalists in each of the ten competitive categories. */
export const FINALISTS: FinalistGroup[] = [
    {
        displayNum: "01",
        category: "Founder of the Year",
        names: [
            "Ahmed Adnan Elsharkawy",
            "Aliaksandr Kazhamiakin",
            "Artem Sokolov",
            "Balamurugan Balasubramanian",
            "Danyi Chen",
            "Dmytro Fedoruk",
            "Georgii Vysotskii",
            "Johnson Fernandes",
            "Rashid Aliyev",
            "Witold Hruzewicz",
        ],
    },
    {
        displayNum: "02",
        category: "Tech & Deep Science Innovation",
        names: [
            "Aswath Ganesan Indra",
            "Cheng Li",
            "David Sikharulidze",
            "Hadeel Ayoub Hill",
            "Johnson Fernandes",
            "Dr Mae Mansoubi, Prof Helen Dawes, Prof Sallie Lamb, Dr Kourosh Norouzi",
            "Manishkumar Yadav",
            "Mary-Brenda Akoda",
            "Mustafa Khanwala",
            "Witold Hruzewicz",
        ],
    },
    {
        displayNum: "03",
        category: "Global Talent Award",
        names: [
            "Professor Adebola Abosede Adeyi",
            "Cansu Deniz Bayrak",
            "David Sikharulidze",
            "Katie Carroll",
            "Lyubov Guk",
            "Melissa Lim",
            "Nsikak John Ekpenyong",
            "Paige Zeigler",
            "Ravneet Kaur",
            "Seyed Aria Nejadghaderi",
        ],
    },
    {
        displayNum: "04",
        category: "Emerging Founder of the Year",
        names: [
            "Aswath Ganesan Indra",
            "Cheng Li",
            "Jian Ma",
            "Maria Sergeeva",
            "Mary-Brenda Akoda",
            "Omid Arbab",
            "Shaofeng (Andy) Wang",
            "Vishal Bhandari",
            "Xinyi Dang",
            "Yuan Xu",
        ],
    },
    {
        displayNum: "05",
        category: "Co-Founding Team of the Year",
        names: [
            "Abhay Arora and Sagar Shah",
            "Dr. David J Maximous, Dr. Tom O'Neil",
            "Edmund Moyo, Dalumuzi 'Muzi' Dube",
            "Heshmatollah Shoja, Omid Arbab",
            "Ismaila Ibrahim",
            "Dr Mae Mansoubi, Prof Helen Dawes, Prof Sallie Lamb, Dr Kourosh Norouzi",
            "Maya Adina Mehrara, Agnese Enricha Picchio",
            "Sonakshi Senthil, Dr Nikhit Anilbhai",
            "Kim Trân Thủy Thiên, Pascal Thanh Tâm Nguyêñ",
            "Vishal Bhandari, Kehinde Ahmed",
        ],
    },
    {
        displayNum: "06",
        category: "Rising Star",
        names: [
            "Adeyinka Ojo",
            "Danyi Chen",
            "Dr. David J Maximous",
            "Dr Manimuthu Arunmozhi",
            "Maria Sergeeva",
            "Mary-Brenda Akoda",
            "Noël Duan",
            "Sanzhar Taizhan",
            "Sean Hayes",
            "Steve Okolo",
        ],
    },
    {
        displayNum: "07",
        category: "Creative & Cultural Innovation",
        names: [
            "Chandni Dangson",
            "Hiroko Shimada",
            "Hyekyung Choi",
            "Joe Javier Huerta Rodriguez",
            "Kartik Sharma",
            "Seyed Aria Nejadghaderi",
            "Tiffany Chiu",
            "Tran Thuy Thien Kim",
            "Xinyi Dang",
            "Yuxin He",
        ],
    },
    {
        displayNum: "08",
        category: "UK SME Global Expansion",
        names: [
            "Abdulrahman Aboutair",
            "Ahmed Adnan Elsharkawy",
            "Dmytro Fedoruk",
            "Heshmatollah Shoja, Omid Arbab",
            "Muhammad Tayyab Shabbir",
            "Mustafa Khanwala",
            "Rashid Aliyev",
            "Sonakshi Senthil, Dr Nikhit Anilbhai",
            "Tiffany Chiu",
            "Witold Hruzewicz",
        ],
    },
    {
        displayNum: "09",
        category: "Breakthrough Innovation of the Year",
        names: [
            "Artem Sokolov",
            "Balamurugan Balasubramanian",
            "Cheng Li",
            "Deepanjan Paul",
            "Dr Abduljabar Hamza",
            "Dr Yogesh Gupta",
            "Fatimah Adeyanre Bamisedun",
            "Ismaila Ibrahim",
            "Mary-Brenda Akoda",
            "Muktari Mohammed Musa",
        ],
    },
    {
        displayNum: "10",
        category: "Ecosystem Builder of the Year",
        names: [
            "Anne-Sophie Martin",
            "Cansu Deniz Bayrak",
            "Lili Zhu",
            "Lyubov Guk",
            "Margaryta Sivakova",
            "Michelle Hua",
            "Nakul Garg",
            "Nelli Shevchenko",
            "Nsikak John Ekpenyong",
            "Ravneet Kaur",
        ],
    },
]
